version: '3.2'

services:
  glorious-tower-postgres:
    image: registry.gitlab.com/goglance/first-hammar:postgres-1572939467
    env_file:
      - staging.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:      
      - core-infra 
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 180s
      placement:
        constraints:
          - node.labels.postgres == true
  
 
volumes:
  postgres-data:          
      driver: rexray/ebs
    

networks:
  core-infra:
    external: true  
