version: '3.2'

services:
  ephemeral-tower-redis:
      image: registry.gitlab.com/goglance/first-hammar:redis-1573641378
      env_file: 
        - staging.env
      volumes:
        - redis-data:/data  
      ports:
        - 6380:6379
      networks:
        - core-infra
      sysctls:
        net.core.somaxconn: 65535
        vm.overcommit_memory: 1
      command: "redis-server /etc/redis/redis.conf"
      deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 10
          window: 180s      
        placement:
          constraints:
            - node.labels.redis == true


volumes:  
  redis-data:
    driver: rexray/ebs 
      
networks:
  core-infra:
    external: true  
