version: '3.2'

services:
  glorious-tower-postgres:
    image: registry.gitlab.com/goglance/first-hammar:postgres-1572939467
    env_file:
      - development.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:      
      - core-infra 
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 180s
      placement:
        constraints:
          - node.labels.postgres == true
  
  ephemeral-tower-redis:
    image: registry.gitlab.com/goglance/first-hammar:redis-1572596611
    env_file: 
      - development.env
    volumes:
      - redis-data:/data  
    ports:
      - 6380:6379
    networks:
      - core-infra
    command: redis-server /etc/redis/redis.conf
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 180s      
      placement:
        constraints:
          - node.labels.redis == true


volumes:
  postgres-data:            
    driver: rexray 
  redis-data:
    driver: rexray 
      

networks:
  core-infra:
    external: true  
