version: '2.2'
services:
  glorious-tower-postgres:
    image: registry.gitlab.com/goglance/first-hammar:postgres-1572534333
    env_file:
      - development.env
    volumes:
      - /home/sidravic/Dropbox/code/workspace/rails_apps/idylmynds/first-hammar/stateful_data/postgres/development:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - development-db-network
      - dev-global-network
  
  ephemeral-tower-redis:
    image: registry.gitlab.com/goglance/first-hammar:redis-1572534629
    env_file: 
      - development.env
    volumes:
      - /home/sidravic/Dropbox/code/workspace/rails_apps/idylmynds/first-hammar/stateful_data/redis/development:/data  
    ports:
      - 6380:6379
    networks:
      - development-db-network
      - dev-global-network
    command: redis-server /etc/redis/redis.conf


networks:
  development-db-network:

  dev-global-network:
    external: true