#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username=$POSTGRES_USER --dbname=$POSTGRES_DB <<-EOSQL
   
    CREATE USER $PG_USERNAME WITH ENCRYPTED PASSWORD '$PG_PASSWORD';

    CREATE DATABASE $PG_DB_NAME;

    GRANT ALL PRIVILEGES ON DATABASE $PG_DB_NAME TO $PG_USERNAME;

    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $PG_USERNAME;
EOSQL