#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username=$POSTGRES_USER --dbname=$POSTGRES_DB <<-EOSQL
   
    CREATE USER $PG_USERNAME WITH ENCRYPTED PASSWORD '$PG_PASSWORD';
    
    \c $POSTGRES_DB;
    
    CREATE EXTENSION IF NOT EXISTS pgcrypto;

    CREATE DATABASE $PG_DB_NAME;    

    \c $PG_DB_NAME

    CREATE EXTENSION IF NOT EXISTS pgcrypto;    

    GRANT ALL PRIVILEGES ON DATABASE $PG_DB_NAME TO $PG_USERNAME;

    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $PG_USERNAME;

    GRANT USAGE ON SCHEMA public to $PG_USERNAME;

    GRANT USAGE ON SCHEMA public to $POSTGRES_USER;
EOSQL